#!/usr/bin/env python3
"""Honest MRMA mechanism table: FULL vs ONES ablation, recomputed from audit.json.

The scientifically correct test of the MRMA masks is NOT instantiation-vs-different-
baseline-model (that conflates architecture with the mask), but FULL vs ONES *within
the same model*: the all-ones mask removes all structure while keeping every parameter
and the training recipe identical. Gain% = relative MSE reduction of FULL over ONES.

Dedup: the audit holds duplicate/divergent runs per cell (different boxes); we take the
BEST (lowest MSE) run for each (model, dataset, pred_len, ablation) -- i.e. we compare
against the strongest available number on both sides, never a crashed/divergent run.

Reads ONLY: /home/ubuntu/honest-ts-bench/results/audit.json  (nothing hardcoded)
Writes:     tables/framework_backbone.tex   (honest ablation summary)
"""
import json, os
from collections import defaultdict

AUDIT = "/home/ubuntu/honest-ts-bench/results/audit.json"
HERE = "/home/ubuntu/ltsf-cc/tslib/paper/multirel-overleaf"
PEMS = ["PEMS03", "PEMS04", "PEMS07", "PEMS08"]
HZ = [12, 24, 48, 96]
PAIRS = [("iTransformer", "MultiRel"),
         ("Crossformer", "SECrossformer"),
         ("S-Mamba", "StructMamba")]

res = json.load(open(AUDIT))["results"]

def best(model, ds, pl, ablset):
    vals = [r["mean_mse"] for r in res
            if r["model"] == model and r["dataset"] == ds and r["pred_len"] == pl
            and r.get("ablation") in ablset and r.get("mean_mse") is not None]
    return min(vals) if vals else None

def ablation_summary(inst):
    helped = total = 0
    gains = []
    for ds in PEMS:
        for pl in HZ:
            full = best(inst, ds, pl, (None, "None"))
            ones = best(inst, ds, pl, ("ONES",))
            if full is None or ones is None:
                continue
            total += 1
            gains.append((ones - full) / ones * 100.0)
            if full < ones:
                helped += 1
    if total == 0:
        return None
    return dict(helped=helped, total=total,
                mean=sum(gains) / len(gains), mx=max(gains))

rows = []
for backbone, inst in PAIRS:
    s = ablation_summary(inst)
    rows.append((backbone, inst, s))

lines = [
    r"% Auto-generated by gen_ablation_honest.py from audit.json -- DO NOT EDIT BY HAND",
    r"% FULL vs ONES mask ablation (same model, structure removed) -- the honest mechanism test.",
    r"\begin{table}[t]",
    r"\centering",
    r"\caption{\textbf{The MRMA masks in isolation.} FULL vs.\ ONES ablation on the "
    r"16 PEMS $\times$ horizon cells: the ONES variant replaces the three relation masks "
    r"with an all-ones mask, keeping every parameter and the training recipe fixed, so the "
    r"only difference is the injected structure. Gain\% is the mean relative MSE reduction "
    r"of FULL over ONES. The masks give large, consistent gains on the single-stage "
    r"attention backbone (\textsc{MultiRel}); their benefit is backbone-dependent.}",
    r"\label{tab:framework_backbone}",
    r"\setlength{\tabcolsep}{5pt}",
    r"\begin{tabular}{llccc}",
    r"\toprule",
    r"Backbone & Instantiation & Masks help & Mean gain\% & Max gain\% \\",
    r"\midrule",
]
for backbone, inst, s in rows:
    name = backbone.replace("_", r"\_")
    if s is None:
        lines.append(f"{name} & {inst} & \\multicolumn{{3}}{{c}}{{ablation in progress}} \\\\")
    else:
        lines.append(f"{name} & {inst} & {s['helped']}/{s['total']} & "
                     f"{s['mean']:+.1f} & {s['mx']:+.1f} \\\\")
lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]

out = os.path.join(HERE, "tables", "framework_backbone.tex")
open(out, "w").write("\n".join(lines) + "\n")
print("wrote", out)
for backbone, inst, s in rows:
    print(f"  {inst:14s}: {s if s else 'PENDING'}")
