#!/usr/bin/env python3
"""Generate framework tables + figure for the AAAI MRMA paper.

EVERY number is recomputed from the verified audit file. Nothing is hardcoded.
Reads ONLY: /home/ubuntu/honest-ts-bench/results/audit.json

Artifacts:
  tables/framework_main.tex     -- headline table (10 baselines vs 3 instantiations)
  tables/framework_backbone.tex -- backbone-improvement summary
  figs/fig_framework_gains.pdf  -- 3-panel relative-gain-vs-horizon figure
"""
import json, os
from collections import defaultdict

AUDIT = "/home/ubuntu/honest-ts-bench/results/audit.json"
HERE = "/home/ubuntu/ltsf-cc/tslib/paper/multirel-overleaf"
os.makedirs(os.path.join(HERE, "tables"), exist_ok=True)
os.makedirs(os.path.join(HERE, "figs"), exist_ok=True)

PEMS = ["PEMS03", "PEMS04", "PEMS07", "PEMS08"]
HZ = [12, 24, 48, 96]
EXCL = ["PUBLISHED", "EXACT OFFICIAL", "PUBLISHED-STYLE", "INTERMEDIATE", "D1024"]

# ---------------------------------------------------------------- load / filter
def is_canonical(x):
    c = str(x.get("config") or "").upper()
    return not any(e in c for e in EXCL)

def is_full_model(x):
    return x.get("ablation") in (None, "None")

def load_cells():
    """Return cell[model][(dataset,pred_len)] = mean_mse, recomputed from seeds."""
    d = json.load(open(AUDIT))
    cell = defaultdict(dict)
    for x in d["results"]:
        if x["dataset"] not in PEMS or x["pred_len"] not in HZ:
            continue
        if not is_canonical(x) or not is_full_model(x):
            continue
        seeds = x.get("seeds_mse", [])
        if len(seeds) < 3:
            continue
        key = (x["model"], x["dataset"], x["pred_len"])
        # recompute the mean from raw seeds (never trust the stored mean)
        mean = sum(seeds) / len(seeds)
        if key[1:] in cell[x["model"]]:
            raise RuntimeError(f"duplicate canonical full entry for {key}")
        cell[x["model"]][key[1:]] = mean
    return cell

CELL = load_cells()

# ---- model groups ------------------------------------------------------------
# 10 baselines; three of them (iTransformer, Crossformer, S-Mamba) are the
# backbones of our instantiations, so they are shown INSIDE the framework
# pairs (once) rather than duplicated in the baselines block.
PAIRS = [  # (backbone, instantiation)
    ("iTransformer", "MultiRel"),
    ("Crossformer", "SECrossformer"),
    ("S-Mamba", "StructMamba"),
]
BACKBONES = [b for b, _ in PAIRS]
INSTANTIATIONS = [i for _, i in PAIRS]
PURE_BASELINES = ["DLinear", "PatchTST", "Autoformer", "FEDformer",
                  "Nonstationary_Transformer", "TimesNet", "TimeMixer"]
# all models that compete for "best per column"
ALL_MODELS = PURE_BASELINES + BACKBONES + INSTANTIATIONS

DISPLAY = {"Nonstationary_Transformer": "Nonstationary"}
def disp(m):
    return DISPLAY.get(m, m)

# columns in order
COLS = [(ds, h) for ds in PEMS for h in HZ]

# per-column minimum across all competing models (the "overall best")
col_min = {}
for col in COLS:
    vals = [CELL[m][col] for m in ALL_MODELS if col in CELL[m]]
    col_min[col] = min(vals)

def fmt(v, best):
    s = f"{v:.3f}"
    return f"\\textbf{{{s}}}" if best else s

def is_best(m, col):
    return col in CELL[m] and abs(CELL[m][col] - col_min[col]) < 1e-9

# ---------------------------------------------------------------- main table
def build_main_table():
    lines = []
    A = lines.append
    A(r"% Auto-generated by gen_framework.py from audit.json -- DO NOT EDIT BY HAND")
    A(r"\begin{table*}[t]")
    A(r"\centering")
    A(r"\caption{Multivariate forecasting MSE on the PEMS traffic benchmarks "
      r"(4 horizons each; 3 seeds, lower is better). Our backbone-agnostic MRMA "
      r"masks yield three instantiations (\textsc{MultiRel}, \textsc{SECrossformer}, "
      r"\textsc{StructMamba}), each shown directly below its backbone. "
      r"\textbf{Bold} marks the best model per column.}")
    A(r"\label{tab:framework_main}")
    A(r"\setlength{\tabcolsep}{4pt}")
    A(r"\resizebox{\textwidth}{!}{%")
    A(r"\begin{tabular}{l" + "cccc" * len(PEMS) + "}")
    A(r"\toprule")
    # dataset header
    dh = ["Model"] + [r"\multicolumn{4}{c}{" + ds + "}" for ds in PEMS]
    A(" & ".join(dh) + r" \\")
    # cmidrule under each dataset group
    cmids = []
    start = 2
    for _ in PEMS:
        cmids.append(fr"\cmidrule(lr){{{start}-{start+3}}}")
        start += 4
    A(" ".join(cmids))
    # horizon header
    hh = [""] + [str(h) for _ in PEMS for h in HZ]
    A(" & ".join(hh) + r" \\")
    A(r"\midrule")

    def row(m, emph=False):
        cells = [fmt(CELL[m][c], is_best(m, c)) for c in COLS]
        name = (r"\textbf{" + disp(m) + "}") if emph else disp(m)
        return name + " & " + " & ".join(cells) + r" \\"

    # baselines block
    for m in PURE_BASELINES:
        A(row(m))
    A(r"\midrule")
    # framework block: backbone then instantiation (bold name = our method)
    for bb, inst in PAIRS:
        A(row(bb))
        A(row(inst, emph=True))
    A(r"\bottomrule")
    A(r"\end{tabular}}")
    A(r"\end{table*}")
    out = os.path.join(HERE, "tables", "framework_main.tex")
    open(out, "w").write("\n".join(lines) + "\n")
    return out

# ---------------------------------------------------------------- backbone table
def compute_backbone_summary():
    """For each (backbone -> instantiation): cells improved / mean gain / max gain."""
    summary = []
    for bb, inst in PAIRS:
        gains = []       # signed relative gain % (positive = instantiation better)
        improved = 0
        for col in COLS:
            if col not in CELL[bb] or col not in CELL[inst]:
                continue
            b = CELL[bb][col]; i = CELL[inst][col]
            g = (b - i) / b * 100.0
            gains.append(g)
            if i < b:
                improved += 1
        mean_gain = sum(gains) / len(gains)
        max_gain = max(gains)
        summary.append(dict(backbone=bb, inst=inst, n=len(gains),
                            improved=improved, mean_gain=mean_gain,
                            max_gain=max_gain, gains=gains))
    return summary

def build_backbone_table(summary):
    lines = []
    A = lines.append
    A(r"% Auto-generated by gen_framework.py from audit.json -- DO NOT EDIT BY HAND")
    A(r"\begin{table}[t]")
    A(r"\centering")
    A(r"\caption{Effect of adding MRMA masks to each backbone across the 16 "
      r"PEMS $\times$ horizon cells. Gain\% is the relative MSE reduction of the "
      r"instantiation over its own backbone.}")
    A(r"\label{tab:framework_backbone}")
    A(r"\setlength{\tabcolsep}{5pt}")
    A(r"\begin{tabular}{llcccc}")
    A(r"\toprule")
    A(r"Backbone & Instantiation & Cells $\downarrow$ & Mean gain\% & Max gain\% \\")
    A(r"\midrule")
    for s in summary:
        A(f"{disp(s['backbone'])} & {disp(s['inst'])} & "
          f"{s['improved']}/{s['n']} & "
          f"{s['mean_gain']:.2f} & {s['max_gain']:.2f} \\\\")
    A(r"\bottomrule")
    A(r"\end{tabular}")
    A(r"\end{table}")
    out = os.path.join(HERE, "tables", "framework_backbone.tex")
    open(out, "w").write("\n".join(lines) + "\n")
    return out

# ---------------------------------------------------------------- figure
def build_figure():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update({
        "font.size": 11, "axes.titlesize": 11, "axes.labelsize": 11,
        "xtick.labelsize": 10, "ytick.labelsize": 10, "legend.fontsize": 9,
        "font.family": "sans-serif", "axes.linewidth": 0.8,
        "pdf.fonttype": 42,
    })
    # categorical palette (fixed order) from the dataviz reference palette
    DS_COLOR = {"PEMS03": "#2a78d6", "PEMS04": "#1baf7a",
                "PEMS07": "#eda100", "PEMS08": "#4a3aa7"}
    MARK = {"PEMS03": "o", "PEMS04": "s", "PEMS07": "^", "PEMS08": "D"}

    fig, axes = plt.subplots(1, 3, figsize=(10.5, 3.3), sharex=True)
    for ax, (bb, inst) in zip(axes, PAIRS):
        mean_across = []
        for h in HZ:
            per = []
            for ds in PEMS:
                col = (ds, h)
                b = CELL[bb][col]; i = CELL[inst][col]
                g = (b - i) / b * 100.0
                per.append(g)
                ax.plot(HZ.index(h), g, MARK[ds], color=DS_COLOR[ds],
                        markersize=6, zorder=3, clip_on=False)
            mean_across.append(sum(per) / len(per))
        # per-dataset lines
        for ds in PEMS:
            ys = [(CELL[bb][(ds, h)] - CELL[inst][(ds, h)]) / CELL[bb][(ds, h)] * 100.0
                  for h in HZ]
            ax.plot(range(len(HZ)), ys, "-", color=DS_COLOR[ds], lw=1.4,
                    alpha=0.85, label=ds, zorder=2)
        # mean-across-datasets line (thick dark)
        ax.plot(range(len(HZ)), mean_across, "-", color="#0b0b0b", lw=2.4,
                label="Mean", zorder=4)
        ax.axhline(0, color="#999999", lw=0.8, ls="--", zorder=1)
        ax.set_title(fr"{disp(inst)} vs {disp(bb)}")
        ax.set_xticks(range(len(HZ)))
        ax.set_xticklabels(HZ)
        ax.set_xlabel("Horizon")
        ax.spines[["top", "right"]].set_visible(False)
        ax.margins(x=0.05)
    axes[0].set_ylabel("Relative MSE gain (\\%)")
    # single shared legend
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=5,
               frameon=False, bbox_to_anchor=(0.5, -0.04))
    fig.tight_layout(rect=(0, 0.04, 1, 1))
    out = os.path.join(HERE, "figs", "fig_framework_gains.pdf")
    fig.savefig(out, bbox_inches="tight")
    plt.close(fig)
    return out

# ---------------------------------------------------------------- run
if __name__ == "__main__":
    t1 = build_main_table()
    summ = compute_backbone_summary()
    # NOTE (2026-07-20): build_backbone_table / build_figure are DISABLED here.
    # compute_backbone_summary compares each instantiation against a DIFFERENT
    # baseline MODEL (e.g. StructMamba vs S-Mamba), which conflates architecture
    # with the mask and produced an overclaim (StructMamba "14/16"). The honest
    # mechanism test is FULL vs ONES within the same model -- see
    # gen_ablation_honest.py (backbone table) and gen_gains_honest.py (figure).
    # Do NOT re-enable these two lines without switching them to the ONES ablation.
    t2 = None  # build_backbone_table(summ)  -- superseded by gen_ablation_honest.py
    f1 = None  # build_figure()              -- superseded by gen_gains_honest.py

    # best-cell count
    best_count = 0
    best_by_model = defaultdict(int)
    for col in COLS:
        for m in INSTANTIATIONS:
            if is_best(m, col):
                best_count += 1
                best_by_model[m] += 1
                break  # count the cell once
    # per-model best tally (may double count if tie, but ties are ~impossible)
    per_model = {m: sum(1 for col in COLS if is_best(m, col)) for m in INSTANTIATIONS}

    print("=== files written ===")
    for p in (t1, t2, f1):
        if p is None:
            continue
        print("  ", p, "OK" if os.path.exists(p) else "MISSING")
    print()
    print("=== backbone summary ===")
    for s in summ:
        print(f"  {s['inst']:14s} vs {s['backbone']:14s}: "
              f"improved {s['improved']}/{s['n']}, "
              f"mean {s['mean_gain']:.2f}%, max {s['max_gain']:.2f}%")
    print()
    print(f"=== best-cell count (an instantiation is overall-best): "
          f"{best_count}/16 ===")
    for m in INSTANTIATIONS:
        print(f"    {m}: {per_model[m]} cells overall-best")
    print()
    print("=== full recomputed matrix (MSE) ===")
    hdr = "model".ljust(16) + "".join(f"{ds}-{h}".rjust(11) for ds in PEMS for h in HZ)
    print(hdr)
    for m in ALL_MODELS:
        row = m[:16].ljust(16)
        for col in COLS:
            v = CELL[m].get(col)
            cellstr = f"{v:.3f}" + ("*" if is_best(m, col) else " ")
            row += cellstr.rjust(11)
        print(row)
